### ISSUE TITLE
4.6.0 is throwing error: Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by todda00** [SupremeTechnopriest/react-idle-timer#153]
The package works with 4.5.6, with 4.6.0 the following error occurs:

```
ReferenceError: regeneratorRuntime is not defined
    at z (webpack-internal:///./node_modules/react-idle-timer/dist/index.es.js:10:14210)
    at eval (webpack-internal:///./node_modules/react-idle-timer/dist/index.es.js:10:24099)
    at commitHookEffectListMount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19731:26)
    at commitPassiveHookEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19769:11)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22853:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/react-dom/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11039:10)
```

I tried both the index.es.js and index.min.js with the same results.

**Comment by SupremeTechnopriest** [comment]
Will look into that.  Must be something missing in my babel config.

**Comment by SupremeTechnopriest** [comment]
Can you tell me which browser is this is failing in?

**Comment by todda00** [comment]
@SupremeTechnopriest Chrome 89, I just tried on Safari 14 and got a slightly different (but same) error:

`ReferenceError: Can't find variable: regeneratorRuntime`

**Comment by todda00** [comment]
FWIW we use babel 7 and webpack 5 to build our app

**Comment by SupremeTechnopriest** [comment]
Okay thats helpful.  Will get back to you shortly.  In the mean time, would you mind testing `npm i react-idle-timer@next`?

**Comment by todda00** [comment]
Just tried `react-idle-timer@next` with the same resulting error.

**Comment by SupremeTechnopriest** [comment]
Okay keep that installed for a bit.  I will push some fix attempts to that tag.

**Comment by SupremeTechnopriest** [comment]
I just published `4.6.1-rc.4` that hopefully fixes your issue.  Can you give it a try on the `@next` tag?

**Comment by todda00** [comment]
🎉 🎉 🎉  `4.6.1-rc.4` fixed the issue!

**Comment by todda00** [comment]
Thanks for knocking that out super quick!

**Comment by SupremeTechnopriest** [comment]
Awesome! I hope to release it today or tomorrow.  In the mean time you can just use the `next` tag and I will update here when it's been released.

**Comment by SupremeTechnopriest** [comment]
No problem. This repo is my baby and I always stay on top of it 🙂

**Comment by SupremeTechnopriest** [comment]
`4.6.1`  is released to NPM.  You can switch back to the `latest` tag now.

**Comment by SupremeTechnopriest** [comment]
`4.6.1`  is released to NPM.  You can switch back to the `latest` tag now.
