### ISSUE TITLE
Illegal invocation

### ISSUE THREAD

**Issue by masterbater** [SupremeTechnopriest/react-idle-timer#234]
Uncaught TypeError: Illegal invocation
    at z (index.esm.js:1:1)
    at index.esm.js:1:1
    at index.esm.js:1:1
    at commitHookEffectListMount (react-dom.development.js:19731:1)
    at commitPassiveHookEffects (react-dom.development.js:19769:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at flushPassiveEffectsImpl (react-dom.development.js:22853:1)
    at unstable_runWithPriority (scheduler.development.js:653:1)
    at runWithPriority$1 (react-dom.development.js:11039:1)
    at flushPassiveEffects (react-dom.development.js:22820:1)
    at react-dom.development.js:22699:1
    at workLoop (scheduler.development.js:597:1)
    at flushWork (scheduler.development.js:552:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:164:1)

**Comment by SupremeTechnopriest** [comment]
Could you show me how you are initializing `IdleTimer`?

**Comment by masterbater** [comment]
import { useIdleTimer } from 'react-idle-timer'

export const App = () => {
  const onIdle = () => {
    // Close Modal Prompt
    // Do some idle action like log out your user
  }

  const onActive = (event) => {
    // Close Modal Prompt
    // Do some active action
  }

  const idleTimer = useIdleTimer({ onIdle, onActive })

  return (
    <div>Test</div>
  )
}

**Comment by masterbater** [comment]
Hello I appreciate your prompt replies. For now I close this because stable version @latest works fine for me not the @next

**Comment by SupremeTechnopriest** [comment]
I will see what I can do to reproduce this and let you know!

**Comment by rikinshah23** [comment]
I tried with the latest version and it gives me the same error. 

I used _A minimal example with the bare essential configuration._

import { useIdleTimer } from 'react-idle-timer'

```
export const App = () => {
  const onIdle = () => {
    // Close Modal Prompt
    // Do some idle action like log out your user
  }

  const onActive = (event) => {
    // Close Modal Prompt
    // Do some active action
  }

  const idleTimer = useIdleTimer({ onIdle, onActive })

  return (
    <HomePage />
  )
}
```

**Comment by rikinshah23** [comment]
I created new [issue](https://github.com/SupremeTechnopriest/react-idle-timer/issues/238) as this is closed.

**Comment by SupremeTechnopriest** [comment]
Illegal invocation fixed in the latest release candidate!
